import { CaptionCue, CaptionStyle } from '../types';

/**
 * Converts a standard hex color string (#RRGGBB or #RRGGBBAA) to ASS ABGR format.
 * ASS uses hexadecimal format &H[AA][BB][GG][RR] where AA is alpha (FF = transparent, 00 = opaque).
 */
function hexToAssColor(hex: string): string {
  const cleanHex = hex.replace('#', '');
  
  if (cleanHex.length === 6) {
    const r = cleanHex.substring(0, 2);
    const g = cleanHex.substring(2, 4);
    const b = cleanHex.substring(4, 6);
    // Fully opaque (alpha = 00 in ASS)
    return `&H00${b}${g}${r}`;
  }
  
  if (cleanHex.length === 8) {
    const r = cleanHex.substring(0, 2);
    const g = cleanHex.substring(2, 4);
    const b = cleanHex.substring(4, 6);
    const a = cleanHex.substring(6, 8);
    // Invert alpha: Web FF (opaque) -> ASS 00 (opaque). Web 00 (transparent) -> ASS FF (transparent).
    const assAlphaVal = 255 - parseInt(a, 16);
    const assAlpha = assAlphaVal.toString(16).padStart(2, '0').toUpperCase();
    return `&H${assAlpha}${b}${g}${r}`;
  }
  
  return '&H00FFFFFF'; // Default opaque white
}

/**
 * Formats a duration in seconds to ASS timestamp format: H:MM:SS.CC (CC = centiseconds)
 */
function formatAssTime(seconds: number): string {
  if (seconds < 0) seconds = 0;
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const cs = Math.floor((seconds % 1) * 100);
  
  const h = hrs.toString();
  const m = mins.toString().padStart(2, '0');
  const s = secs.toString().padStart(2, '0');
  const c = cs.toString().padStart(2, '0');
  
  return `${h}:${m}:${s}.${c}`;
}

/**
 * Generates ASS subtitle contents based on caption cues and style preferences.
 */
export function generateAssSubtitles(cues: CaptionCue[], style: CaptionStyle): string {
  const fontName = style.fontFamily;
  const fontSize = style.fontSize;
  
  // Karaoke logic:
  // - PrimaryColour: The color the text changes to after being spoken (Highlight color)
  // - SecondaryColour: The default text color before being spoken (Text color)
  const primaryAssColor = hexToAssColor(style.highlightColor);
  const secondaryAssColor = hexToAssColor(style.textColor);
  const outlineAssColor = hexToAssColor(style.outlineColor);
  const shadowAssColor = hexToAssColor(style.shadowColor);
  
  const outlineWidth = style.outlineWidth;
  const shadowWidth = style.shadowBlur;
  
  let borderStyle = 1; // 1 = Outline + drop shadow
  let backColor = shadowAssColor;
  
  // Check if we should render a solid background box
  if (style.backgroundColor && style.backgroundColor !== 'transparent' && style.backgroundColor !== '') {
    borderStyle = 3; // 3 = Opaque bounding box
    backColor = hexToAssColor(style.backgroundColor);
  }
  
  let playResX = 1080;
  let playResY = 1080;

  if (style.aspectRatio === '9:16') {
    playResX = 1080;
    playResY = 1920;
  } else if (style.aspectRatio === '16:9') {
    playResX = 1920;
    playResY = 1080;
  } else if (style.aspectRatio === '4:5') {
    playResX = 1080;
    playResY = 1350;
  }

  const marginV = Math.round(((100 - style.positionY) / 100) * playResY);

  let ass = `[Script Info]
; Script generated by Bleach
ScriptType: v4.00+
PlayResX: ${playResX}
PlayResY: ${playResY}
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Custom,${fontName},${fontSize},${primaryAssColor},${secondaryAssColor},${outlineAssColor},${backColor},-1,0,0,0,100,100,0,0,${borderStyle},${outlineWidth},${shadowWidth},2,10,10,${marginV},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  cues.forEach(cue => {
    const startTimeStr = formatAssTime(cue.start);
    const endTimeStr = formatAssTime(cue.end);
    
    // Create copy for local text transformation
    let processedCueText = cue.text;
    let processedWords = cue.words.map(w => ({ ...w }));

    // Apply casing transformation
    if (style.caseStyle === 'upper') {
      processedWords = processedWords.map(w => ({ ...w, word: w.word.toUpperCase() }));
      processedCueText = processedCueText.toUpperCase();
    } else if (style.caseStyle === 'sentence') {
      processedWords = processedWords.map((w, index) => {
        if (index === 0 && w.word.length > 0) {
          return { ...w, word: w.word.charAt(0).toUpperCase() + w.word.slice(1) };
        }
        return w;
      });
      processedCueText = processedWords.map(w => w.word).join(' ');
    }

    // Build the subtitle text with karaoke timing tags (\k)
    let assText = '';
    let lastTime = cue.start;

    for (let i = 0; i < processedWords.length; i++) {
      const w = processedWords[i];
      
      // Calculate silence/gap before this word
      const gap = w.start - lastTime;
      if (gap > 0.01) {
        const gapCs = Math.round(gap * 100);
        assText += `{\\k${gapCs}}`;
      }
      
      // Calculate active word duration in centiseconds
      const duration = w.end - w.start;
      const durationCs = Math.max(1, Math.round(duration * 100));
      
      // Remove any brackets to avoid breaking ASS tag brackets
      const escapedWord = w.word.replace(/[{}]/g, '');
      
      // Add karaoke tag and word text
      assText += `{\\k${durationCs}}${escapedWord}`;
      
      // Add trailing space if it's not the last word
      if (i < processedWords.length - 1) {
        assText += ' ';
      }
      
      lastTime = w.end;
    }
    
    // Calculate final gap to cue boundary
    const endGap = cue.end - lastTime;
    if (endGap > 0.01) {
      const endGapCs = Math.round(endGap * 100);
      assText += `{\\k${endGapCs}}`;
    }

    ass += `Dialogue: 0,${startTimeStr},${endTimeStr},Custom,,0,0,0,,${assText}\n`;
  });

  return ass;
}
